package:
  name: mqc
  version: "1.0"

source:
  url: https://github.com/Biobix/mQC/archive/v1.0.tar.gz
  md5: 69f6dca89a1068007bf3543685861be7
  sha1: 27bc7d4c628af129f2939e74a9759cc2d5dbc6a8
  sha256: 85a0a7ff79c8c8d18ca062187cc50a361bee1000d8e63bebb8ecfe8d9deefc32

build:
  rpaths:
    - lib/R/lib
    - lib/
  skip: True  # [not py27]

requirements:
  build:
    - libgcc # [linux]
    - llvm # [osx]
    - python
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - r-base
    - perl
    - perl-app-cpanminus
    - perl-dbi
    - perl-parallel-forkmanager
  run:
    - libgcc # [linux]
    - llvm # [osx]
    - python
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - r-base
    - perl
    - perl-app-cpanminus
    - perl-dbi
    - perl-parallel-forkmanager

test:
  commands:
    - mQC.pl --help

about:
  home: https://github.com/Biobix/mQC
  license: GNU General Public License v3.0
  license_file: LICENSE
  summary: qualtiy control tool to assess the mapping quality of a ribosome profiling experiment
